//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> IdStudent { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
