
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WpfApp1.Bd
{

using System;
    using System.Collections.Generic;
    
public partial class Progress
{

    public int ID { get; set; }

    public Nullable<int> IdStudent { get; set; }

    public Nullable<int> IdItem { get; set; }

    public Nullable<int> IdMark { get; set; }



    public virtual Item Item { get; set; }

    public virtual Mark Mark { get; set; }

    public virtual Student Student { get; set; }

}

}
