//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int ID { get; set; }
        public string Name_Teacher { get; set; }
        public Nullable<int> IdObject { get; set; }
        public Nullable<int> IdCabinet { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Item Item { get; set; }
    }
}
