//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int ID { get; set; }
        public string Name_Teacher { get; set; }
        public Nullable<int> IdObject { get; set; }
        public Nullable<int> IdCabinet { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Item Item { get; set; }
    }
}
